"""Go SDK client generator for the AumOS SDK.

Generates idiomatic Go client code from an OpenAPI specification for the AumOS
Go SDK's `_generated/` layer. Produces Go struct definitions, service types,
context-aware methods, APIError types, and functional options for client configuration.
"""

import re
from typing import Any

# OpenAPI type → Go type mappings
_OPENAPI_TO_GO_TYPES: dict[str, str] = {
    "string": "string",
    "integer": "int64",
    "number": "float64",
    "boolean": "bool",
    "array": "[]",
    "object": "map[string]interface{}",
}

# Go format-specific overrides
_FORMAT_TO_GO: dict[str, str] = {
    "uuid": "string",
    "date-time": "time.Time",
    "date": "string",
    "int32": "int32",
    "int64": "int64",
    "float": "float32",
    "double": "float64",
    "email": "string",
    "uri": "string",
}

# Go file header
_GO_HEADER_TEMPLATE: str = """\
// Code generated by AumOS SDK codegen. DO NOT EDIT.
// Source: openapi/aumos-api.yaml
// Regenerate: make generate-go

package generated

import (
\t"context"
\t"encoding/json"
\t"fmt"
\t"io"
\t"net/http"
\t"net/url"
\t"time"
)
"""


class GoClientGenerator:
    """Generates idiomatic Go client code from an OpenAPI specification.

    Produces Go struct definitions with JSON tags, service types with
    context-aware methods, functional options for client construction,
    APIError type implementing the error interface, and pagination helpers.
    All generated code targets Go 1.21+ idioms.
    """

    def __init__(
        self,
        package_name: str = "generated",
        module_path: str = "github.com/aumos/aumos-sdk-go",
        api_base_url: str = "https://api.aumos.ai",
    ) -> None:
        """Initialise the Go client generator.

        Args:
            package_name: Go package name for generated code.
            module_path: Go module path (go.mod module directive).
            api_base_url: Default base URL for the generated client.
        """
        self._package_name = package_name
        self._module_path = module_path
        self._api_base_url = api_base_url

    def generate_struct(
        self,
        struct_name: str,
        schema: dict[str, Any],
    ) -> str:
        """Generate a Go struct from an OpenAPI schema.

        Args:
            struct_name: Go struct name (PascalCase).
            schema: OpenAPI JSON schema dict.

        Returns:
            Go source string for the struct definition.
        """
        properties = schema.get("properties", {})
        required_fields = set(schema.get("required", []))
        description = schema.get("description", f"AumOS {struct_name} type.")

        lines: list[str] = [
            f"// {struct_name} {description}",
            f"type {struct_name} struct {{",
        ]

        for prop_name, prop_schema in properties.items():
            go_type = self._resolve_type(prop_schema)
            go_field_name = self._to_pascal_case(prop_name)
            is_required = prop_name in required_fields

            if not is_required and not go_type.startswith("*"):
                pointer_type = f"*{go_type}" if not go_type.startswith("[]") else go_type
            else:
                pointer_type = go_type

            omitempty = "" if is_required else ",omitempty"
            prop_description = prop_schema.get("description", "")
            if prop_description:
                lines.append(f"\t// {prop_description}")
            lines.append(
                f'\t{go_field_name} {pointer_type} `json:"{prop_name}{omitempty}"`'
            )

        lines.append("}")
        return "\n".join(lines)

    def generate_api_error_type(self) -> str:
        """Generate the Go APIError type implementing the error interface.

        Returns:
            Go source string for the APIError struct and methods.
        """
        return '''\
// APIError represents an error response from the AumOS API.
type APIError struct {
\tStatusCode int    // HTTP status code
\tMessage    string // Human-readable error message
\tErrorCode  string // AumOS platform error code
\tRequestID  string // Request trace identifier
}

// Error implements the error interface.
func (e *APIError) Error() string {
\tif e.RequestID != "" {
\t\treturn fmt.Sprintf("AumOS API error %d: %s (request_id=%s)", e.StatusCode, e.Message, e.RequestID)
\t}
\treturn fmt.Sprintf("AumOS API error %d: %s", e.StatusCode, e.Message)
}

// IsRetryable returns true for server-side transient errors.
func (e *APIError) IsRetryable() bool {
\treturn e.StatusCode == 429 || (e.StatusCode >= 500 && e.StatusCode < 600)
}

// IsAuthError returns true for authentication/authorization failures.
func (e *APIError) IsAuthError() bool {
\treturn e.StatusCode == 401 || e.StatusCode == 403
}

// IsNotFound returns true when the requested resource was not found.
func (e *APIError) IsNotFound() bool {
\treturn e.StatusCode == 404
}
'''

    def generate_client_struct(self) -> str:
        """Generate the root Go client struct and constructor with functional options.

        Returns:
            Go source string for the Client struct, options, and NewClient function.
        """
        return f'''\
// Client is the root AumOS API client.
type Client struct {{
\tbaseURL    string
\thttpClient *http.Client
\tapiKey     string
}}

// ClientOption is a functional option for configuring the Client.
type ClientOption func(*Client)

// WithAPIKey sets the API key for authentication.
func WithAPIKey(key string) ClientOption {{
\treturn func(c *Client) {{
\t\tc.apiKey = key
\t}}
}}

// WithBaseURL overrides the default API base URL.
func WithBaseURL(u string) ClientOption {{
\treturn func(c *Client) {{
\t\tc.baseURL = u
\t}}
}}

// WithHTTPClient sets a custom *http.Client for the SDK.
func WithHTTPClient(client *http.Client) ClientOption {{
\treturn func(c *Client) {{
\t\tc.httpClient = client
\t}}
}}

// NewClient creates a new AumOS Client with the provided options.
func NewClient(opts ...ClientOption) *Client {{
\tc := &Client{{
\t\tbaseURL:    "{self._api_base_url}",
\t\thttpClient: &http.Client{{Timeout: 30 * time.Second}},
\t}}
\tfor _, opt := range opts {{
\t\topt(c)
\t}}
\treturn c
}}

// doRequest executes an HTTP request and decodes the JSON response.
func (c *Client) doRequest(ctx context.Context, method, path string, body io.Reader, result interface{{}}) error {{
\tu, err := url.JoinPath(c.baseURL, path)
\tif err != nil {{
\t\treturn fmt.Errorf("invalid URL: %w", err)
\t}}

\treq, err := http.NewRequestWithContext(ctx, method, u, body)
\tif err != nil {{
\t\treturn fmt.Errorf("creating request: %w", err)
\t}}

\treq.Header.Set("Content-Type", "application/json")
\treq.Header.Set("Accept", "application/json")
\tif c.apiKey != "" {{
\t\treq.Header.Set("Authorization", "Bearer "+c.apiKey)
\t}}

\tresp, err := c.httpClient.Do(req)
\tif err != nil {{
\t\treturn fmt.Errorf("executing request: %w", err)
\t}}
\tdefer resp.Body.Close()

\tif resp.StatusCode >= 400 {{
\t\treturn c.parseErrorResponse(resp)
\t}}

\tif result != nil {{
\t\tif err := json.NewDecoder(resp.Body).Decode(result); err != nil {{
\t\t\treturn fmt.Errorf("decoding response: %w", err)
\t\t}}
\t}}
\treturn nil
}}

func (c *Client) parseErrorResponse(resp *http.Response) error {{
\tvar errBody struct {{
\t\tMessage   string `json:"message"`
\t\tErrorCode string `json:"error_code"`
\t\tRequestID string `json:"request_id"`
\t}}
\t_ = json.NewDecoder(resp.Body).Decode(&errBody)
\treturn &APIError{{
\t\tStatusCode: resp.StatusCode,
\t\tMessage:    errBody.Message,
\t\tErrorCode:  errBody.ErrorCode,
\t\tRequestID:  errBody.RequestID,
\t}}
}}
'''

    def generate_service_type(
        self,
        service_name: str,
        operations: list[dict[str, Any]],
    ) -> str:
        """Generate a Go service type for a group of API operations.

        Args:
            service_name: Service type name (e.g., 'AgentsService').
            operations: List of operation dicts.

        Returns:
            Go source string for the service type and methods.
        """
        lines: list[str] = [
            f"// {service_name} provides methods for the {service_name.replace('Service', '').lower()} API.",
            f"type {service_name} struct {{",
            "\tclient *Client",
            "}",
            "",
        ]

        for operation in operations:
            method_source = self._generate_operation_method(operation, service_name)
            lines.append(method_source)

        return "\n".join(lines)

    def generate_page_struct(self, item_type: str) -> str:
        """Generate a typed pagination response struct for a given item type.

        Args:
            item_type: Go type name for page items (e.g., 'Agent').

        Returns:
            Go source string for the Page struct.
        """
        page_name = f"{item_type}Page"
        return (
            f"// {page_name} is a paginated response containing {item_type} items.\n"
            f"type {page_name} struct {{\n"
            f'\tItems    []{item_type} `json:"items"`\n'
            f'\tTotal    int         `json:"total"`\n'
            f'\tPage     int         `json:"page"`\n'
            f'\tPageSize int         `json:"page_size"`\n'
            f'\tPages    int         `json:"pages"`\n'
            f"}}\n"
        )

    def generate_all_structs(self, spec: dict[str, Any]) -> str:
        """Generate all Go struct definitions from the OpenAPI spec's component schemas.

        Args:
            spec: OpenAPI spec dict.

        Returns:
            Go source string with all struct definitions.
        """
        schemas = spec.get("components", {}).get("schemas", {})
        parts: list[str] = [_GO_HEADER_TEMPLATE, ""]

        for schema_name in sorted(schemas):
            struct_source = self.generate_struct(schema_name, schemas[schema_name])
            parts.extend([struct_source, ""])

        return "\n".join(parts)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _resolve_type(self, schema: dict[str, Any]) -> str:
        """Resolve an OpenAPI property schema to a Go type string.

        Args:
            schema: OpenAPI property schema dict.

        Returns:
            Go type string.
        """
        ref = schema.get("$ref", "")
        if ref:
            return ref.split("/")[-1]

        schema_format = schema.get("format", "")
        if schema_format in _FORMAT_TO_GO:
            return _FORMAT_TO_GO[schema_format]

        schema_type = schema.get("type", "object")
        if schema_type == "array":
            item_schema = schema.get("items", {})
            item_type = self._resolve_type(item_schema)
            return f"[]{item_type}"

        return _OPENAPI_TO_GO_TYPES.get(schema_type, "interface{}")

    def _to_pascal_case(self, name: str) -> str:
        """Convert a camelCase or snake_case name to PascalCase for Go fields.

        Args:
            name: Input identifier string.

        Returns:
            PascalCase Go identifier.
        """
        parts = re.split(r"[_\-]", name)
        return "".join(p.capitalize() for p in parts if p)

    def _generate_operation_method(
        self,
        operation: dict[str, Any],
        service_name: str,
    ) -> str:
        """Generate a Go method for a single API operation on a service type.

        Args:
            operation: Operation dict.
            service_name: Owning service type name.

        Returns:
            Go source string for the service method.
        """
        method_name = self._derive_method_name(operation)
        http_method = operation.get("method", "GET")
        path = operation.get("path", "/")
        summary = operation.get("summary", f"Call {http_method} {path}.")

        path_params = re.findall(r"\{(\w+)\}", path)
        go_params = ["ctx context.Context"]
        go_params.extend(f"{p} string" for p in path_params)

        params_str = ", ".join(go_params)
        go_path = path
        for param in path_params:
            go_path = go_path.replace(f"{{{param}}}", '"+'+param+'+"')
        go_path = go_path.strip("+")

        return (
            f"// {method_name} {summary}\n"
            f"func (s *{service_name}) {method_name}({params_str}) (map[string]interface{{}}, error) {{\n"
            f'\tvar result map[string]interface{{}}\n'
            f'\tif err := s.client.doRequest(ctx, "{http_method}", "{path}", nil, &result); err != nil {{\n'
            f"\t\treturn nil, err\n"
            f"\t}}\n"
            f"\treturn result, nil\n"
            f"}}\n"
        )

    def _derive_method_name(self, operation: dict[str, Any]) -> str:
        """Derive a PascalCase Go method name from an operation.

        Args:
            operation: Operation dict.

        Returns:
            PascalCase Go method name.
        """
        operation_id = operation.get("operation_id", "")
        if operation_id:
            return self._to_pascal_case(operation_id)

        method = operation.get("method", "GET").capitalize()
        path_parts = operation.get("path", "").strip("/").split("/")
        resource = "".join(p.capitalize() for p in path_parts if not p.startswith("{"))
        return f"{method}{resource}"
